parameters:
- name: environment
  displayName: 'List of environments'
  type: object
  default:
    - 'dv'
    - 'stg'
    - 'prd'
- name: pipeline_id
  default: '17'

trigger:
  branches:
    include:
      - main

stages:
- ${{ each value in parameters.environment }}:
  - stage: DATABRICKS_CD_${{ upper(value) }}
    displayName: 'DATABRICKS_CD_${{ upper(value) }}'
    jobs:
    - deployment: DATABRICKS_DEPLOY_${{ upper(value) }}
      displayName: 'DATABRICKS_DEPLOY_${{ upper(value) }}'
      environment: ${{ value }}
      strategy:
        runOnce:
          deploy:
            steps:
              - template: templates/databricks/steps-cd.yml
                parameters:
                  environment: ${{ value }}
                  service_connection: '${{ value }}_service_connection'
                  artifactDir: 'artifact'
                  pipeline_id: ${{ parameters.pipeline_id }}